name: fitnesstracker
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.5
  get: ^4.6.6
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/gotogymBOY.png
  image_dark: assets/images/gotogymBOY.png
  fullscreen: true
  android_12:
   image: assets/images/gotogymBOY.png
   image_dark: assets/images/gotogymBOY.png
   icon_backgroud_color: "#f7f6f1"
   icon_backgroud_color_dark: "#272727"
   fullscreen: true

  


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/splash_images/
    - assets/images/welcome_images/    
    - assets/images/login_image/ 
    - assets/logos/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
